global:
  scrape_interval:     5s # By default, scrape targets every 5 seconds.
scrape_configs:
  - job_name: 'sd_configs'
    ec2_sd_configs:
     - region: eu-west-1
       port: 9095
    relabel_configs:
     - source_labels: [__meta_ec2_tag_Environment]
       regex: staging
       action: keep
     - source_labels: [__meta_ec2_tag_Name]
       target_label: instance
